#version: '3.8'

services:
  backend:
    build:
      context: ./plump
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./backend:/app
      - ./plump/prisma/dev.db:/app/prisma/dev.db
    environment:
      - DATABASE_URL=file:./prisma/data/dev.db
      - JWT_SECRET=mySecretKey

  frontend:
    build:
      context: ./project-management-ui
      dockerfile: Dockerfile
    ports:
      - "8080:80" 
    environment:
      - JWT_SECRET=mySecretKey
    depends_on:
      - backend 
